### PR TITLE
Fix exported CMake package

### PR DESCRIPTION
**Pull request by andschwa**
This fixes our project to export a mostly usable [CMake package](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-packages). It's been loosely tested against @Lusitanian's code base.

### CODE REVIEW

**Comment by andschwa** [comment]
Yay it worked (although the error message is misleading).

**Comment by andschwa** [comment]
Oh, wait, shoot.

**Comment by andschwa** [comment]
Oh... #1411 didn't actually go in. My bad.

**Comment by andschwa** [comment]
This pretty much implements #887, but we should still add our own samples/docs/tests before the next release, especially considering the `oeedger8r` hack.

**Comment by andschwa** [comment]
bors try

**Comment by andschwa** [comment]
Uh those failures make no sense to me, this built on my machine 😢

**Comment by andschwa** [comment]
Caching and scoping problems... figures.

bors try

**Comment by andschwa** [comment]
The bors try is about to fail due to flaky 18.04 tests, but otherwise succeeded 🎉

**Comment by anitagov** [comment]
I disagree with the comment "flaky tests" causing failures on the new Ubuntu 18.04 Jenkins stages. 
@ionutbalutoiu has been trying to address these Jenkin stages getting aborted by increasing the timeout/adding extra workers, etc. Please read his update on PR #1428

**Comment by anitagov** [comment]
What is the meaning of "flaky 18.04 tests"?  
@ionutbalutoiu has been trying to address the Ubuntu 18.04 Jenkin stages getting aborted by increasing the timeout/adding extra workers, etc. Please read his update on PR #1428.
But CI run on master still has various failures in multiple stages including Ubuntu 16.04.

**Pull request merged**
