### PR TITLE
Added CI/CD new node documentation.

### PR DESCRIPTION
**Pull request by johnkord**

### CODE REVIEW

**Comment by CodeMonkeyLeet** [comment]
@johnkord Can we consolidate MS-specific configuration for CI/CD elsewhere? The repo is public and this is not information that can be consumed by a general audience.

**Comment by johnkord** [comment]
@CodeMonkeyLeet That's fine with me. I wasn't really sure where this document should go. Maybe a sharepoint?

**Comment by andschwa** [comment]
Oh goodness, not a SharePoint. Private docs repo a good compromise?

**Comment by johnkord** [comment]
@andschwa Sure that's fine with me too. How do we go about creating a private GitHub repo under the MS org?

**Comment by CodeMonkeyLeet** [comment]
@andschwa @johnkord Yes, that sounds good to me. I would just like to avoid confusing the public.

**Pull request closed without merging**
