### PR TITLE
WinOE work - oecore built/worked.

### PR DESCRIPTION
**Pull request by bmhsieh**
- Implemented dispatch code between host and enclave. 
- oecore (enclave\core) built on Windows.
- The test "ecall" linked with stub CRT functions oecore.lib passed. (Test modification not included in this PR).

### CODE REVIEW

**Comment by bmhsieh** [comment]
bors try

**Comment by bmhsieh** [comment]
bors try

**Comment by anitagov** [comment]
@bmhsieh - Can you please add a few lines to description?

**Comment by johnkord** [comment]
We are cherry picking fixes from the PR and not accepting it entirely.

**Pull request closed without merging**
