### PR TITLE
Skip more Windows simulation tests

### PR DESCRIPTION
**Pull request by oprinmarius**
Disable more flaky Windows simulation tests as identified here:  https://github.com/Microsoft/openenclave/issues/1474

### CODE REVIEW

**Comment by oprinmarius** [comment]
bors try

**Comment by ionutbalutoiu** [comment]
bors try

**Comment by ionutbalutoiu** [comment]
bors try

**Comment by CodeMonkeyLeet** [comment]
@anakrish Can you take a look at this? Based on your findings for the GS/FS register handling on Windows simulation mode, it seems like all tests that use enclaves have the potential to fail, and it's not clear to me that the set identified here is sufficient.

**Comment by anakrish** [comment]
@johnkord @ionutbalutoiu @aserdean We recently found out that simulation mode does not work in windows. We need to change GS/FS register values and Windows would restore it to the original values whenever it resumes a thread.

We need to disable the simulation mode stages on windows.

**Comment by ionutbalutoiu** [comment]
@anakrish Thank-you for letting us know. So far, the CI doesn't have any Windows simulation enabled in the current upstream `master` branch.

This PR was part of the effort to get something up and running. Let's have this in the backlog until we're ready to merge it upstream.

**Comment by johnkord** [comment]
@ionutbalutoiu For now I'm going to close this PR, we can re-open it at a later point

**Pull request closed without merging**
