### PR TITLE
Add checks for cmake

### LINKED ISSUE #1432: Maybe add checks for cmake in a new CI stage
Maybe add the following arguments `--warn-uninitialized  -Wdev` to cmake invocations.

Also `--warn-unused-vars` would be nice if we filter out the noise.

CC: @andschwa

### PR DESCRIPTION
**Pull request by oprinmarius**
Add `--warn-uninitialized -Wdev --warn-unused-vars` to cmake invocations.
Addresses #1432

### CODE REVIEW

**Comment by oprinmarius** [comment]
bors try

**Comment by anitagov** [comment]
I updated the description to reflect all the checks being made.
Nice if you can make this an env variable in Jenkins and pass it around as we do with all the other flags. This is repetitive and long.
--warn-uninitialized -Wdev --warn-unused-vars

**Comment by oprinmarius** [comment]
bors try

**Comment by oprinmarius** [comment]
bors try

**Pull request merged**
