### PR TITLE
[samples] Remove unused target from local/remote attestation Makefiles

### PR DESCRIPTION
**Pull request by aserdean**
Signed-off-by: Alin Gabriel Serdean <aserdean@ovn.org>

### CODE REVIEW

**Comment by aserdean** [comment]
Reported-at: https://github.com/Microsoft/openenclave/pull/1570#discussion_r266449464

**Comment by andschwa** [comment]
Are there `genkey` targets in those two `Makefiles`?

**Comment by aserdean** [comment]
I'm not sure if I was clear in the issue/commit message. Let's take a local attestation as an example:
Top level: https://github.com/Microsoft/openenclave/blob/master/samples/local_attestation/Makefile#L6
Enclave A:
https://github.com/Microsoft/openenclave/blob/master/samples/local_attestation/enc1/Makefile#L24-L25
Enclave B:
https://github.com/Microsoft/openenclave/blob/master/samples/local_attestation/enc2/Makefile#L24-L25

The `genkey` target from A and B is used, however the `Top level` `genkey` isn't used.

This patch just removes the top level ones. I guess it is similar to the conf file which wasn't removed  during a refactor.

**Comment by aserdean** [comment]
bors try

**Comment by anitagov** [comment]
It seems that this change went into the master without @soccerGB approval. The top level genkey invokes the 2 enclaves genkey and can be used to generate the keys for both the enclaves. I do not agree with this change.

**Comment by johnkord** [comment]
I'm tagged on this PR so I'm not sure of the full context for this, but it looks like the genkey targets are redundant at the outer Makefile level, so removing these targets+rules should be fine. If the enclave's key doesn't exist, each enclave's "all" target appears to invoke their own "genkey" target (and the other's genkey target) and generate their signing/verifying keys. Please correct me if I'm wrong, @soccerGB  :)

**Comment by anitagov** [comment]
Tagging @gupta-ak as he made this change. I reckon this is to generate keys if needed at the top level by using "make genkey" - seems handy. @gupta-ak - please comment on why you added this.

**Pull request merged**
