### PR TITLE
De-duplicate package installation logic

### PR DESCRIPTION
**Pull request by oprinmarius**
* Added ansible tasks equivalent for the following scripts:
scripts/install-prereqs => .jenkins/ansible/tasks/ansible-install-prereqs.yml
scripts/install-open-enclave-stack => .jenkins/ansible/tasks/ansible-install-openenclave-stack.yml

* Re-wrote .jenkins/Dockerfile and .jenkins/Dockerfile.scripts to use ansible-playbooks for building the image
.jenkins/Dockerfile => .jenkins/ansible/ansible-dockerfile.yml
.jenkins/Dockerfile.scripts => .jenkins/ansible/ansible-dockerfile-scripts.yml

* deploy_jenkins.yml , ansible-dockerfile.yml and ansible-dockerfile-scripts.yml  include the same tasks in their play

* Added .jenkins/ansible/install-ansible.sh and .jenkins/ansible/remove-ansible.sh scripts to install and remove ansible

### CODE REVIEW

**Comment by oprinmarius** [comment]
bors try

**Comment by oprinmarius** [comment]
bors try

**Comment by oprinmarius** [comment]
bors try

**Comment by oprinmarius** [comment]
bors try

**Comment by andschwa** [comment]
Oh! Also, can we move the ansible folder from '.jenkins' to 'scripts/ansible'?

**Pull request merged**
