### PR TITLE
Added nightly libc tests into normal test runs.

### PR DESCRIPTION
**Pull request by johnkord**
This also disables all references to the ENABLE_FULL_LIBC_TESTS flags. As part of this change, the nightly libc tests will be disabled from running, due to these tests now being run as part of CI.

This enables around ~200 libc tests to be run in our CI and should prevent future changes to OE from breaking our integration with libc.

This change implements the linux side of #1188.

### CODE REVIEW

**Comment by johnkord** [comment]
bors try

**Comment by anitagov** [comment]
Do you want to deprecate or delete the libc_tests.Jenkinsfile with this PR?

**Comment by johnkord** [comment]
bors r+

> 
> 
> Do you want to deprecate or delete the libc_tests.Jenkinsfile with this PR?

Yes, I will do that, great idea. Thanks Anita!

**Comment by anitagov** [comment]
@andschwa - No, it doesn't replace #782 and assumed that #782 had been merged to master. So, #782 still needs to be completed in the master.

**Pull request merged**
