### PR TITLE
Make OE_DEPRECATED macro be compiler agnostic

### PR DESCRIPTION
**Pull request by dthaler**
Addresses Issue #869

Signed-off-by: Dave Thaler <dthaler@microsoft.com>

### CODE REVIEW

**Comment by paulcallen** [comment]
bors ping

**Comment by paulcallen** [comment]
bors ping

**Comment by paulcallen** [comment]
@dthaler maybe bors does not like this because the source repository fork is gone?

**Comment by dthaler** [comment]
Quite possibly yes, making the master repo public broke some things.  I'll repush it.

**Comment by dthaler** [comment]
Replaced by PR #898

**Pull request closed without merging**
