### PR TITLE
Convert libc unittest to edger8r

### PR DESCRIPTION
**Pull request by EMumau**

### CODE REVIEW

**Comment by anitagov** [comment]
@EMumau - Please verify that your changes PASS all the 270 libc tests i.e. with the ENABLE_FULL_LIBC_TESTS cmake flag enabled on all the configurations. This is not the default CI run. You can run the Jenkins libc Pipeline on your branch.

**Comment by EMumau** [comment]
Added the missing edl file.

**Comment by EMumau** [comment]
bors try

**Pull request merged**
