### PR TITLE
convert props unittest to edger8r

### PR DESCRIPTION
**Pull request by EMumau**

### CODE REVIEW

**Comment by gupta-ak** [comment]
@EMumau do you want to change the commit authorship to your username? It's currently Ubuntu

**Comment by EMumau** [comment]
@gupta-ak I've wasted a lot of time trying to change the author.  I see no value in spending anymore time on the matter.  I did update my config file to avoid that occurring in the future.

**Comment by anitagov** [comment]
@EMumau - I was able to fix this last week. Once you update your config file, issue the following command to modify the previous commit. 
git commit --amend --reset-author --no-edit

For the previous commits, you will need to rebase to that point, etc. which you can skip if you wish but definitely doable. Here is the link:
https://stackoverflow.com/questions/750172/how-to-change-the-author-and-committer-name-and-e-mail-of-multiple-commits-in-gi

**Comment by anitagov** [comment]
bors try

**Comment by johnkord** [comment]
bors try

**Comment by paulcallen** [comment]
bors try

**Comment by paulcallen** [comment]
bors try

**Comment by paulcallen** [comment]
bors try

**Comment by andschwa** [comment]
@EMumau @anitagov Just for future reference, I documented the steps to fix commit authorship [here](https://github.com/Microsoft/openenclave/blob/master/docs/Contributing.md#commit-messages). It is not a "nice-to-have" it's a Microsoft-legal requirement that code authorship (and thus copyright) is clearly maintained, hence why this does need to be done correctly. I am sorry for the trouble it caused.

**Comment by andschwa** [comment]
@paulcallen More `bors try` isn't going to fix it, Bors is waiting for Jenkins to update the try commit with a status hook.

**Comment by EMumau** [comment]
bors try

**Pull request merged**
