### PR TITLE
Remove the need for maintained docker images

### PR DESCRIPTION
**Pull request by oprinmarius**
Changed Jenkinsfile to build oetools image and use docker cached layers instead of pulling pre-built image from private registry

### CODE REVIEW

**Comment by andschwa** [comment]
I think this is way easier than manually maintaining a private Docker registry with our image 👍 

bors try

**Comment by oprinmarius** [comment]
> @johnkord I am totally down for and love this change. We just need to check ordering and document how to purge those caches (or consider if that's even necessary, since I think that Docker should notice a change to a Dockerfile and then create new layers for updated packages).

Dockerfile won't change since it is just including an ansible playbook.
It is adding the scripts/ansible folder before starting the build though. So any changes to the scripts/ansible/ folder would trigger new builds since the first layer is changed.

**Comment by andschwa** [comment]
That addresses my concern! Oh I am excited for this 😂

**Comment by andschwa** [comment]
John and I figured out ordering, as this PR conflicts with a few other open ones. We're going to merge this first as it _should_ reduce the work in later PRs by eliminating the need to manually update the Docker image.

bors r+

Thanks!

**Pull request merged**
