### PR TITLE
Improve Ansible prereq setup for OE

### PR DESCRIPTION
**Pull request by ionutbalutoiu**
* Update the `SimulatorGettingStarted.md` doc
* Use the existing `requirements.txt` file for Ansible when
  installing / removing the tool into `install-ansible.sh` or
  `remove-ansible.sh` bash scripts

### CODE REVIEW

**Comment by ionutbalutoiu** [comment]
bors try

**Comment by aserdean** [comment]
Thanks for fixing the doc 👍 .

/LGTM

**Comment by ionutbalutoiu** [comment]
Fixed some small linter problems

**Pull request merged**
