### PR TITLE
Build enclaves on Windows using clang cross compilation (phase 1)

### PR DESCRIPTION
**Pull request by anakrish**
All the enclave libraries are built in this changelist.
The tests will be built in phase 2.

1. Pass -DBUILD_ENCLAVES=1 on windows to turn on the feature.
2. Introduces clangw (clang-wrapper) to handle mix of msvc and gcc/clang options generated by cmake.
3. Uses ld.lld to link enclaves. llvm-ar to create libraries.
4. Launches git-bash as needed to do necessary configurations for some targets (especially 3rdparty).

This contains the same changes as from #1255; but with a simpler history.

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors r+
Merging this in after discussion with @johnkord

**Comment by andschwa** [comment]
🎉

**Pull request merged**
