### PR TITLE
Added -DBUILD_ENCLAVES=1 flag to Windows CI builds.

### PR DESCRIPTION
**Pull request by johnkord**
This relies on this new flag being defined in #1255

### CODE REVIEW

**Comment by johnkord** [comment]
We should test both configurations, actually. I'm going to modify this so this flag is parameterized

**Comment by andschwa** [comment]
bors try

**Comment by anakrish** [comment]
@johnkord Do we need an entry for "NMake Makefiles" in https://github.com/Microsoft/openenclave/blob/master/CMakeSettings.json ?

**Comment by johnkord** [comment]
@anakrish probably! I usually don't touch that file because I've yet to use VisualStudio/Code for building. I'll make that change once #1255 goes in and I can test it :)

**Pull request closed without merging**
