### PR TITLE
changes needed to build on windows using clang.

### PR DESCRIPTION
**Pull request by yakman2020**

### CODE REVIEW

**Comment by yakman2020** [comment]
bors try

**Comment by andschwa** [comment]
@yakman2020 Your commits are still not linking to your GitHub account. Is this intentional?

**Comment by andschwa** [comment]
@yakman2020 Should we close this?

**Comment by yakman2020** [comment]
Nope. I'll update.

**Comment by CodeMonkeyLeet** [comment]
Closing this out for the following reasons:

- We don’t have plans to support compiling host in clang on Windows and we don’t document instructions for building host in clang on Windows.
- It’s not clear that the changes are sufficient or necessary any more
    - The instructions for Windows deployment now suggest LLVM 7.0+ and as far as I can tell, clang supports C11 (`static_assert`) and has an immintrin.h that defines `_readgsbase_u64`/`_writegsbase_u64` (which is currently used with the basic MSVC compile)
- This PR can’t be easily rebased on master any more due to the folder layout changes for integration with Trustzone.

**Pull request closed without merging**
