### PR TITLE
Skip std_containers_associative_map_map.access_at test on GCC >7 release builds

### PR DESCRIPTION
**Pull request by aserdean**
Signed-off-by: Alin Gabriel Serdean <aserdean@ovn.org>

### CODE REVIEW

**Comment by ionutbalutoiu** [comment]
@johnkord @andschwa 

Do you think we can get this in before branching for release ?

It fixes https://github.com/Microsoft/openenclave/issues/1559

**Comment by johnkord** [comment]
@ionutbalutoiu Is this one of the tests that pass for gcc 8, but not gcc 7? Or does this fail for gcc 8 as well?

**Comment by aserdean** [comment]
@johnkord I haven't tested with GCC 8. I used for testing only 5 and 7(default shipped by Ubuntu 1804).

**Comment by johnkord** [comment]
Okay, thanks Alin.

bors r+

**Comment by ionutbalutoiu** [comment]
@johnkord 

I manually tried the GCC 8 full libcxx run using the `Release` build type, and everything worked as expected there.

I have `RelWithDebinfo` and `Debug` still running, but this problem doesn't seem to appear on GCC 8. 

However, I had to ignore a particular error for some of tests. [This](https://github.com/ionutbalutoiu/openenclave/commit/892af1048fc7c31db8688a9f93ab26c824800c4f) what I had to do to successfully compile full libcxx with GCC 8 on Ubuntu 18.04.

**Pull request merged**
