### PR TITLE
Use cmake to build oeedger8r instead of make.

### PR DESCRIPTION
**Pull request by anakrish**
1. Generate Lexer and Parser in binary-dir.
2. Use ocamlopt to compile files in correct order
   and generate executable.
3. Add dependency to all source files and
   generated lexer and parser.
4. Remove makefile

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Comment by paulcallen** [comment]
bors try

**Pull request merged**
