### PR TITLE
WIP - samples CMake

### PR DESCRIPTION
**Pull request by aserdean**
Signed-off-by: Alin Gabriel Serdean <aserdean@ovn.org>

### CODE REVIEW

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try-

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try -

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try-

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try

**Comment by aserdean** [comment]
bors try

**Comment by andschwa** [comment]
I'm going to close this for as we don't want to integrate the samples into OE's CMake build.

**Pull request closed without merging**
