### PR TITLE
Make oe_random be public in enclave.h

### PR DESCRIPTION
**Pull request by dthaler**
Addresses Issue #832

Signed-off-by: Dave Thaler <dthaler@microsoft.com>

### CODE REVIEW

**Comment by CodeMonkeyLeet** [comment]
@dthaler If the intent to make `oe_random` a public equivalent to `sgx_read_rand` then the fix should not be to move it into /bits, but into enclave.h directly.

If we would like to defer implementing matching semantics for `oe_random`, we should track that as a separate issue:
- existing semantics for an internal host-enclave convergence function `oe_internal_random` should keep its existing implementation
- `oe_random` as a public analog of `sgx_read_rand` would be implemented on top of an internal implementation of `rdrand` shared with `mbedtls_hardware_poll`

**Comment by CodeMonkeyLeet** [comment]
@dthaler yes, I agree that you can expose the API first and then change the implementation later, I was just asking for it to be tracked as an issue. The change I would like for this particular PR is just that we have the naming and the export to enclave.h, and we're good to go.

**Comment by dthaler** [comment]
Need to replace this PR with a new one due to the private/public permission changes on repos.

**Comment by dthaler** [comment]
Replaced with PR #888

**Pull request closed without merging**
