### PR TITLE
Fix GCC warnings on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by andschwa**
This should unblock #1256.

### CODE REVIEW

**Comment by andschwa** [comment]
This is part of unblocking #1256, but there is more to do.

@gupta-ak I added comments to clarify that confusing MUSL build 😂

**Comment by andschwa** [comment]
@johnkord can I please get another review? I believe I've addressed the rest of the problems. This built on my local Ubuntu 18.04 machine.

**Comment by andschwa** [comment]
bors try

**Comment by andschwa** [comment]
Ignore a warning introduced by an additional warning 😅 

bors try

**Comment by andschwa** [comment]
bors try

**Comment by andschwa** [comment]
More explicit version checking...

bors try

**Comment by andschwa** [comment]
🤕 

bors try

**Comment by andschwa** [comment]
Phew, just format-code (how did that sneak by?!)

**Comment by andschwa** [comment]
@johnkord @mikbras I'd appreciate a review.

**Comment by johnkord** [comment]
This unrelated issue that is causing these CI runs to fail is happening extremely frequently now, and not just during the afternoon it looks like. It is currently being investigated, so let's cross our fingers and try staging again:

bors r+

**Pull request merged**
