### PR TITLE
Add KDF to mbedtls

### PR DESCRIPTION
**Pull request by achamayou**
We would like to use mbedtls' key derivation function implementation.

### CODE REVIEW

**Comment by achamayou** [comment]
bors try

**Comment by anakrish** [comment]
@johnkord @CodeMonkeyLeet Can you review this PR?

**Comment by johnkord** [comment]
This seems good to me

**Comment by anitagov** [comment]
@achamayou - If there any mbedtls functional tests that exercise this new functionality, can you please add those to the tests/mbed suite and ensure that they Pass? Thanks.

**Comment by CodeMonkeyLeet** [comment]
I think it's fine to unblock Coco, though we need to have the options we enable be reviewed again by the crypto folks. In particular, the SDL guidance has always been to use NIST SP800-108 for KDF which HKDF is slightly outside the scope of. We'll need an expert to verify whether mbedtls HKDF is compliant with SP800-56Cr1 though it looks pretty standard to me. 

Side note: Akash has actually implemented SP800-108 under the common folder for the TrustZone folks, so that is actually available, at least internally in the SDK.

**Comment by achamayou** [comment]
@anitagov I will have a look, and do what's necessary if there are tests.

@CodeMonkeyLeet If the implementation in common/ is accessible/public, we could use it instead, but we'd prefer not to implement our own KDF.

**Comment by achamayou** [comment]
@anitagov there are tests, but unfortunately, neither they nor the hkdf implementation is in the current version of mbedtls that's in OpenEnclave, so this is blocked by https://github.com/Microsoft/openenclave/pull/1419

I will rebase and add the tests once this is in.

**Comment by johnkord** [comment]
Is this still needed?

**Comment by achamayou** [comment]
@johnkord yes, but until mbedtls is upgraded, this won't help. The feature was added in July '16 (https://github.com/ARMmbed/mbedtls/commit/656864b3605fde3d6ac127453a9442bb9a29e5cc#diff-ae73d78afdb2244b10fdbdd32337c0de), but OE currently uses 2.7.

2.7 is currently LTS, and will be until Feb 2021. Assuming that OE continues its policy of shipping against the mbedtls LTS, that will mean a 4.5+ year lead time on this particular feature.

**Pull request closed without merging**
