### PR TITLE
Fixing Windows CI build.

### PR DESCRIPTION
**Pull request by johnkord**
Right now Windows builds in CI are broken (the tests aren't getting run and powershell is erroring out, yet it believes it to be a successful build), and this PR will revert the changes that broke it.

This PR temporarily disables the oeedgr8r tests on Windows, which needs to be re-enabled ASAP.

### CODE REVIEW

**Comment by johnkord** [comment]
For example, look at the build output here for the powershell script for the Windows stage: https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/289/pipeline/32

**Comment by johnkord** [comment]
bors try

**Comment by johnkord** [comment]
Note that the extra commit here (deleting the "linuxbin" directory) is to get CI to pass on Windows. The Jenkins agent on Windows is not cleaning the Jenkins workspace before or after the build properly, even though it is configured to do so. That seems like a bug with the Jenkins agent.  To remedy this, we now force remove the "linuxbin" directory before the build to make sure that it is wiped away.

**Comment by andschwa** [comment]
Oh yeah, PowerShell doesn't usually report the exit code of native processes back to the process which spawned PowerShell. This bites everyone.

**Comment by andschwa** [comment]
You can do it in PowerShell, you just have to wrap the execution of the native binaries and instruct PowerShell to `throw` when they fail. Here's how [we do it in PowerShell's own build script](https://github.com/PowerShell/PowerShell/blob/3794a5e39f31ebacfc2ec2e9ad687c9bf3772cba/build.psm1#L2006).

**Comment by johnkord** [comment]
bors try

**Comment by johnkord** [comment]
bors try

**Comment by johnkord** [comment]
bors try

**Comment by johnkord** [comment]
bors try

**Comment by anitagov** [comment]
Great job John. Windows CI giving a False PASS wasn't good.

**Pull request merged**
