### PR TITLE
Please dont review: Using branch for testing : Clean up of OE_USE_LIBSGX

### PR DESCRIPTION
**Pull request by radhikaj**
This is purely for experimental purposes. Please dont review

### CODE REVIEW

**Comment by anitagov** [comment]
Radhika: You can fire a sandbox run to stabilize your branch before issuing a PR. Trust this helps.

**Comment by radhikaj** [comment]
bors try

**Comment by radhikaj** [comment]
bors try

**Comment by radhikaj** [comment]
Closing experimental pull request and opening an actual one

**Pull request closed without merging**
