### PR TITLE
Wnd/test enable

### PR DESCRIPTION
**Pull request by sushantstripathi**
Re-enable tests for ELF enclave on Windows #1033

### CODE REVIEW

**Comment by sushantstripathi** [comment]
bors try

**Comment by CodeMonkeyLeet** [comment]
bors try

**Comment by johnkord** [comment]
Make sure not to merge this to master until we get our Windows CI builds working. Right now they're letting everything pass. I'll try to remember to post back in this conversation when the Windows CI builds work again, but if I don't post back here, feel free to @ me

**Comment by johnkord** [comment]
bors try

**Comment by johnkord** [comment]
Note that Windows CI is back online and functional, so feel free to run bors commands from here on out.

**Comment by anakrish** [comment]
@anitagov @johnkord Can you fix the conflicts and get this PR in today?

**Comment by johnkord** [comment]
@anakrish I will work on this today! Thanks for letting me know :)

**Comment by anitagov** [comment]
@anakrish - As I mentioned to @johnkord, I will work on this PR as I enabled 16 ELF tests recently with my PR #1172. Thanks for letting me know.


- Anita

________________________________

**Comment by anitagov** [comment]
With my PR #1217 , I am able to reduce the enclave size for ecall_ocall even further. The CMakeSettings.json in this PR seems like an acceptable change. However, I am not setup to test WSL but can rope this change with my PR #1217 .
tests/CMakeLists.txt - Several of the tests that being enabled in this PR have already been enabled or still continue to Fail on Windows. So, the master supersedes this file.

**Comment by anitagov** [comment]
With my PR #1217 , I am able to reduce the enclave size for ecall_ocall even further. The CMakeSettings.json in this PR seems like an acceptable change. However, I am not setup to test WSL but can rope this change with my PR #1217 .
tests/CMakeLists.txt - Several of the tests that are being enabled in this PR have already been enabled or still continue to Fail on Windows. Will enable additional tests that are now Passing with PR #1217 and then close out this PR.

**Comment by anitagov** [comment]
Closing this as PR #1217 supersedes this.

**Pull request closed without merging**
