### PR TITLE
Add one stage to make sure GNU make builds continue to work on Linux

### PR DESCRIPTION
**Pull request by EmilAlexandruStoica**
Added new stage to test the build using Make.

Fixes https://github.com/Microsoft/openenclave/issues/1481

### CODE REVIEW

**Comment by andschwa** [comment]
@EmilAlexandruStoica Could you please check your committer settings? GitHub isn't picking up your account, and I think your name just came through as your user login. Thanks!

**Comment by EmilAlexandruStoica** [comment]
@andschwa I changed my settings, now it should be fine.

**Comment by andschwa** [comment]
Thanks @EmilAlexandruStoica!

**Pull request merged**
