### PR TITLE
Removed requirement to source /etc/environment from ansible install prereqs

### LINKED ISSUE #1308: Ansible-playbook shouldn't require sourcing of /etc/environment for CMake binaries availability in PATH
A proposed solution to this is to create symbolic links in a normal path for binaries that point to the installed CMake binaries.

### PR DESCRIPTION
**Pull request by johnkord**
This fixes #1308

### CODE REVIEW

**Comment by anitagov** [comment]
Looks good John. Can you please verify that OE build works fine if cmake isn't in /usr/bin?

**Comment by johnkord** [comment]
@anitagov I've verified that it works! Here's my user's default PATH on an ACC VM:

johnkord@acclnx:~$ echo $PATH
/home/johnkord/bin:/home/johnkord/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by anitagov** [comment]
This is great. Thanks John

**Comment by johnkord** [comment]
@oprinmarius @ionutbalutoiu That's really nice! Love it

**Comment by johnkord** [comment]
weird, the jenkins job didn't trigger from the last command. I'll try again!

bors r+

**Comment by andschwa** [comment]
@johnkord There's a really strange error in the [webhook logs](https://github.com/Microsoft/openenclave/settings/hooks/42551606). It says it failed to deliver push event  `dfc6b77c-15d4-11e9-9709-dc602672368e` because "the payload was too large?!?" I am not sure if that was the push from the first bors r+ or not, but it's soooo weird.

**Comment by johnkord** [comment]
@andschwa That's a wild error! Well, hopefully we don't hit it again. If it occurs again, we'll look at it in more detail.

Unrelated: Fixed whitespace issue (apparently these matter in ansible .yml files!) and force-pushed 

bors r+

**Pull request merged**
