### PR TITLE
Change Jenkinsfile to scripted

### PR DESCRIPTION
**Pull request by oprinmarius**
Change Jenkinsfile to scripted
Added cleanWs() and checkout scm for all tests
Added PowerShellWrapper to detect powershell scripts failures

### CODE REVIEW

**Comment by oprinmarius** [comment]
bors try

**Comment by oprinmarius** [comment]
bors try

**Comment by dragoshsch** [comment]
bors try

**Comment by dragoshsch** [comment]
bors try

**Comment by dragoshsch** [comment]
bors try

**Pull request merged**
