### PR TITLE
Removed hard-coding CC and CXX env variables for ninja

### PR DESCRIPTION
**Pull request by anitagov**
Fixed one of the Windows CI platforms yesterday as Visual Studio Tools was not configured correctly. Verified that cmake picks up the correct MSVC compiler (cl.exe) instead of clang-7.0 for ninja builds. 
So, don't need the hard-coded CC and CXX env variables which was added as a temporary workaround with PR # 1415.

### CODE REVIEW

**Comment by anitagov** [comment]
bors try

**Comment by andschwa** [comment]
Should these still be defined for the non-Ninja generator? Sorry, I'm not quite sure what the original bug was and how this resolves it. Would you mind explaining a bit please?

**Comment by anitagov** [comment]
Different libcxx tests are failing with Ubuntu 18.04 Linux CI runs since PR #1434

**Comment by anitagov** [comment]
Closing this as this Power shell script has been deprecated with the PR #1428 . This PR also does not hard code the env variables CC and CXX, so the essence of my PR has been incorporated.

**Pull request closed without merging**
